apiVersion: batch/v1
kind: Job
metadata:
  name: destroy-rancher
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: destroy-rancher
    spec:
      containers:
      - name: destroy-rancher
        image: docker.io/library/ez-rancher
        command:
         - "terraform"
         - "destroy"
         - "-input=false"
         - "-auto-approve"
         - "-var-file=/tfvars/terraform.tfvars"
         - "-state=/deliverables/terraform.tfstate"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: tfvars
            mountPath: /tfvars
          - name: volv
            mountPath: /deliverables
      volumes:
        - name: tfvars
          configMap:
            name: ez-rancher
        - name: volv
          persistentVolumeClaim:
            claimName: standard-volv-pvc
      restartPolicy: Never
